### ISSUE TITLE
不行啊，报错，提示找不到文件

### ISSUE THREAD

**Issue by CalllMeJump** [mrzcpoGit/Notion_Chinese_All#1]

**Comment by mrzcpoGit** [comment]
> 

notion版本号 和 安装路径提供一下

**Comment by CallMeJump** [comment]
最新版3.9.6
路径：C:\Users\14919\AppData\Local\Programs\Notion
![image-20240708144554693](https://github.com/mrzcpoGit/Notion_Chinese_All/assets/50916063/9391227e-86a5-424c-8095-b1b304eabf72)

**Comment by mrzcpoGit** [comment]
https://github.com/mrzcpoGit/Notion_Chinese_All/releases/download/Main/notionAssetCache-v2.zip
把这个文件解压到%appdata%\Notion目录下，再运行试试，应该是Notion刚刚安装，资源文件没加载好

![1720430895996](https://github.com/mrzcpoGit/Notion_Chinese_All/assets/53836837/7e21f3a9-b327-4ce4-b7c5-f0a39c5eaad8)

**Comment by CallMeJump** [comment]
可以了，多谢大佬

**Comment by mrzcpoGit** [comment]
有人用我的软件，我很开心，谢谢

**Comment by CallMeJump** [comment]
大佬加油

**Comment by difengsheng** [comment]
> https://github.com/mrzcpoGit/Notion_Chinese_All/releases/download/Main/notionAssetCache-v2.zip 把这个文件解压到%appdata%\Notion目录下，再运行试试，应该是Notion刚刚安装，资源文件没加载好
> 
> ![1720430895996](https://github.com/mrzcpoGit/Notion_Chinese_All/assets/53836837/7e21f3a9-b327-4ce4-b7c5-f0a39c5eaad8)

这个目录没有找到呀，我自定义的按住那个路径是在D盘
